### PR TITLE
Added support for selecting the special layer levels

### LINKED ISSUE #286: Add support for creation of missing layer level types
Allow the creation/setting of layers of all special map levels:
- `object1`
- `object2`
- `object3`
- `last`
- `first`
- `light`
- `postlight`

Currently, the only way to set layers to this are by manually going into the JSON map data. The map editor already has support for rendering/saving these layers (albeit displaying them on "level 10"), the only thing missing is the user being able to set them.

Related to issue #157.

### PR DESCRIPTION
**Pull request by EL20202**
Adds in support for selecting all the special level types in a layer - specifically `first`, `last`, `light`, `postlight`, `object1`, `object2`, and `object3`. The map editor already has support for loading (and saving) layers with named levels, this merely adds the ability for one to select them (as well as properly displaying them in the layer selector). 

For example, by loading up the map `autumn/path-3-1` in the current version of the map editor, followed by the same map loaded with the new support:
image image

As for the selector for the layer levels:
image

These changes also follow the current behavior of the map editor - it treats `first` as though it is level 0, and every other level as though it was level 10.

Closes #286 and #157.

### CODE REVIEW

**Comment by Vegita2** [comment]
Is it possible to make `first` be always below level 0? I noticed it in a few maps that first is sometimes drawn on top of another layer on level 0

**Comment by EL20202** [comment]
I'll see what I can do, I have some ideas on how that could be accomplished.

**Comment by EL20202** [comment]
There, I think that should do it - from my quick tests with `jungle/path-01-entrance.json` (which has a layer at `first`), I didn't have any issues, especially with going into 3D, which is where I expected to have issues.

**Comment by EL20202** [comment]
There, I added the changelog. Everything should be ready now.

**Review by Vegita2 — CHANGES_REQUESTED** [review]
good addition.

I thought level -1 would cause some issues, but I couldn't find any problems with it.

**Comment by EL20202** [comment]
There, made the requested changes. And yeah - I too was a little surprised too how level -1 didn't break much of anything - if anything at all.

**Review by 2767mr — APPROVED** [review]

**Review by Vegita2 — APPROVED** [review]

**Pull request merged**
